
import 'package:edirne_gezgini_ui/model/enum/base_place_category.dart';
import 'package:edirne_gezgini_ui/model/enum/restaurant_category.dart';
import 'package:edirne_gezgini_ui/model/restaurant.dart';

import '../model/accommodation.dart';
import '../model/enum/accommodation_category.dart';
import '../model/enum/place_category.dart';
import '../model/favorite.dart';
import '../model/place.dart';
import '../model/restaurant.dart';
import '../model/toVisit.dart';

class TemporaryDatabase{
  //create a singleton to access this class statically
  static final _singleton = TemporaryDatabase._internal();

  factory TemporaryDatabase(){
    return _singleton;
  }

  TemporaryDatabase._internal();

  List<Place> places = [
    Place(title: "Selimiye Camii", image: "images/selimiye.jpg", category: PlaceCategory.historical, location: "Meydan, Mimar Sinan Cd., 22020 Edirne Merkez/Edirne ", info: "Edirne’nin her yerinden tüm ihtişamı ile görülebilen, dört zarif minaresi, muhteşem kubbesi ile eşsiz bir yapı olan Selimiye Camii dünya tarihinin ünlü mimarlarından birisi olan Mimar Sinan’ın eseridir. Yapımına II.Selim’in emri ile 1568 yılında başlanan caminin inşası binlerce kişinin yoğun çalışması ile yedi yıl sürmüş ve 1575 yılında tamamlanmıştır. Osmanlı mimarisinin en önemli eseri olarak kabul edilen camiyi Mimar Sinan da “ustalık eserim” olarak tanımlamıştır.İlk olarak anıtsal görünümü ile dikkat çeken Selimiye Camii’nin dört köşesinde yer alan, her biri üç şerefeli minareleri ,dünyanın en görkemli örnekleri arasında gösterilmektedir. Caminin minarelerinin uzunluğu alemleri dahil 85,67 metre olarak ölçülmüştür. Minarelerin mimari açıdan dikkat çekici yönleri, mümkün olabilecek en ince şekilde tasarlanmaları ve her birinde birbiriyle çakışmadan ayrı ayrı şerefelere ulaşan üçer merdivenin bulunmasıdır.Osmanlı İmparatorluğu’nun İstanbul’dan önce başkentliğini yapmış Edirne şehrindeki Selimiye Camii ve Külliyesi, 2011 yılında UNESCO Dünya Miras Listesi’ne dahil edilmiştir."),
    Place(title: "Sultan II. Beyazid Külliyesi", image: "images/külliye1.jpg", category: PlaceCategory.historical, location: "Yeniimaret, 22000 Edirne Merkez/Edirne ", info: "Tunca Nehri kıyısında bulunan İkinci Bayezid Külliyesi Sağlık Müzesi, Edirne’nin en önemli yapıtlarındandır. Cami; tıp medresesi, imaret, darüşşifa, hamam, mutfak, erzak depoları ve öbür bölümleriyle geniş bir alana yayılmıştır.Darüşşifa'da özellikle akıl hastalarının müzik ve su sesiyle iyileştirilmesi ana ilkeydi. Ayrıca külliyenin göz tedavisi için de yine önemli bir merkez olduğu anlatılmaktadır. Külliye bütünüyle kültür tarihi yönünden önemlidir. Bu bölüm günümüzde Sağlık Müzesi olarak hizmet vermektedir. Sultan II. Bayezid Külliyesi'ni oluşturan ve o dönemde akıl hastalıklarının müzik ve su sesi ile tedavi edildiği “Şifahane ve Tıp Medresesi” Trakya Üniversitesi tarafından İkinci Bayezid Külliyesi Sağlık Müzesi'ne dönüştürülmüştür.  "),
    Place(title: "Karaağaç", image: "images/tren garı.jpg", category: PlaceCategory.historical, location: "Karaağaç 22100 Edirne Merkez/Edirne ", info: "16. yüzyıldan önceki kaynaklarda adına rastlanmayan Karaağaç, topograﬁk konumu itibarıyla Edirne'ye oranla yüksek bir mevkide bulunması, orman ve nehirlerle çevrilmiş olması sebebiyle Edirne merkeze oranla özellikle yaz aylarının daha serin geçmesi ve şehre yakın olması nedeniyle bir sayfiye yeri olmuştur. Kaynaklarda Karaağaç'ın bir Rum köyü olduğu, Edirnelilerin yazlık evlerinin bu köyde bulunduğu ve köyün o zaman için, çevre halkı tarafından mesirelik ve eğlence bölgesi özelliğini taşıdığı anlatılmaktadır. "),
    Place(title: "Meriç Köprüsü", image: "images/meric.jpg", category: PlaceCategory.historical, location: "Karaağaç, 22100 Edirne Merkez/Edirne ", info: "Meriç Köprüsü, 1842'de Abdülmecid zamanında yapımına başlanmış ve 1847'de bitirilmiş köprüdür.[1] Edirne-Karaağaç yolunda, Meriç nehri üzerinde yer alır. 263 metre uzunluk, 7 metre genişlikte, 13 ayak üzerinde 12 sivri kemerli olup yanlara doğru eğimli özellikler taşımaktadır. Mermer yazıtlı tarih köşkü olan köprünün kubbesinde daha önceleri güneş motifi şeklinde demirden bir paratoner olduğu bilinmektedir.dirne’nin 19. yüzyılda inşa edilmiş Osmanlı dönemine ait son taş köprüsü olan yapı tarihi ve mimari özellikleri yanında ayakları üzerindeki figürlü kabartma taş süslemeleriyle de dikkati çekmektedir. Bunlar arasında yılan şeklindeki çift ejder figürü, uygulandığı dönem ve bir köprü üzerinde yer alıyor olması nedeniyle ayrı bir öneme sahiptir. Ayrıca kabartma şeklinde bir ay yıldız motifi ve üst üste üç sıra halindeki kuş tünekleri de yapıyı özel kılan diğer unsurlardır. "),
    Place(title: "Üç Şerefeli Camii", image: "images/üçşerefelicamii.jpg", category: PlaceCategory.historical, location: "Babademirtaş, 22000 Edirne Merkez/Edirne ", info: " 1433-1447 yılları arasında. II.Murat'ın yaptırdığı Cami Osmanlı Sanatının erken ve klasik dönem üslubu arasında yar alır. Burada ilk kez uygulanan bir planla karşılaşılmaktadır. 24 m. çapındaki büyük merkezi kubbe, ikisi paye, dördü duvar paye olmak üzere altı dayanağa oturur. Yanında daha küçük ikişer kubbe ile örtülü kare bölümler vardır. Yapı, bir yenilik olarak enine dikdörtgen bir yapıdır. Böylece enine gelişen mekana ulaşılmak istenmiştir. Bu planı Mimar Sinan İstanbul camilerinde daha gelişmiş biçimiyle uygulamıştır. Ayrıca, Osmanlı mimarisinde revaklı avlu ilk kez bu camide kullanılmıştır. Avlunun dört köşesine minareler yerleştirilmiştir. Üç Şerefeli Cami, bu özellikleriyle sonraki camilere öncü olan anıtsal bir yapıdır. Revak kubbelerindeki özgün kalem işleri Osmanlı camilerindeki en eski örneklerdendir. Camiye adını veren üç şerefeli anıtsal minare, 67,62 m. yüksekliğindedir. Her şerefeye ayrı yollardan çıkılması ilginçtir. Minare kırmızı taştan zikzaklar ve ak karelerle devinim kazanmıştır"),
    Place(title: "Lozan Anıtı", image: "images/lozan-anıtı.jpg", category: PlaceCategory.historical, location: " Karaağaç, İstasyon Cd., 22100 Edirne Merkez/Edirne", info: " Edirne'nin Karaağaç semtinde yer alan ve 1972 yılına kadar da tren istasyonu olarak kullanılan bina, bu tarihten itibaren Trakya Üniversitesi'ne devredilerek Trakya Üniversitesi’nin çeşitli birimlerini barındırmış ve sosyal tesis olarak kullanılmıştır. Bina günümüzde Trakya Üniversitesi Güzel Sanatlar Fakültesi olarak kullanılmaktadır. Burada yer alan Lozan Anıtı, Meydanı ve Müzesi'nin 19 Temmuz 1998 günü açılışı yapılmıştır."),
    Place(title: "Edirne Arkeoloji ve Etnografya Müzesi", image: "images/etnografya.jpg", category: PlaceCategory.museum, location: "Meydan, Kadir Paşa Mektep Sk., 22020 Edirne Merkez/Edirne", info: "Arkeoloji ve Etnografya seksiyonu olmak üzere, iki seksiyondan oluşmaktadır."
        "Arkeoloji Seksiyonu: Sergileme Paleontolojik döneme ait fosillerle başlar. Bu bölümde Edirne ve yakın çevresinde bulunan 3. Zaman sonuna ait fil, gergedan ve at türünden hayvanların defans, çene kemiği, diş ve omurlarına ait parçalar vardır."
        "Etnografya Seksiyonu: 94 yıl boyunca Osmanlı İmparatorluğuna başkentlik eden Edirne XVII. Yüzyılda dünyanın dördüncü büyük kenti olarak bilinmektedir. Sergilemede bu özgün kültürün yansımaları dikkat çekmektedir. Gelin ve sünnet odasında bulunan halılar, işlemeler, edirnekari yüklükler devrin sanat değeri yüksek değerli eserleridir. Hamam Köşesi, Edirne Oturma Odası Köşesi, Edirne Evleri Keten Sıva Örnekleri, çeşitli işleme ve kıyafetler ile takılar, oyalar ve Topkapı Sarayı Müzesi tarafından hediye edilen tombak ibrikler, buhurdanlıklar, güllebdanlar dikkati çekmektedir. "),
    Place(title: "Türk ve İslam Eserleri Müzesi", image: "images/islam.jpg", category: PlaceCategory.museum, location: " Meydan, Zehrimar Cami Sok., 22020 Edirne Merkez/Edirne", info: "Edirne'de ilk müze Atatürk'ün talimatıyla 1925 yılında Selimiye Camii Dar-ül Hadis Medresesi'nde kurulmuştur. Osmanlı İmparatorluğu'nun yaklaşık 94 yıl başkentliğini yapan Edirne'de saray, halk sanatlarını etkilemiş ve etnografya açısından zenginlik kazandırmıştır. Bu yüzden ikinci bir müzeye gerek duyulmuştur.Selimiye Camii avlusu içinde bulunan Dar-üs Sıbyan Medresesi'nin, restore ettirilmesiyle Etnografya adı altında ikinci bir bölüm, Edirne'nin kurtuluşunun 13'üncü yılında (25 Kasım 1936) burada açılmıştır.İkinci Dünya Savaşından sonra Edirne Müzelerindeki eserlerin birçoğunun müzelere geri verilmesi sonucu elde kalanlar yalnızca Dar-ül Hadis Medresesi'nde sergilenmiştir.Bundan sonraki yıllarda satın alma, bağış ve kazılardan gelen eserlerle müzedeki eserlerin sayısının artması nedeniyle Edirne'de ihtiyaç duyulan yeni bir müze binası 1966 yılında programa alınmıştır. Selimiye Camii civarında müze için temin edilen arsa üzerine yapılan müze binası, 13 Haziran 1971 yılında Arkeoloji ve Etnografya Müzesi adı ile açılmış, Dar-ül Hadis Medresesindeki Müze de Türk İslam Eserleri Müzesi olarak düzenlenmiştir. "),
    Place(title: "Edirne Kent Müzesi", image: "images/edirne-kent-muzesi.jpg", category: PlaceCategory.museum, location: " Babademirtaş, Hacı Hasan Sk. No:11, 22020 Edirne Merkez/Edirne ", info: "Kentin ekonomik, sosyolojik, kültürel yönlerini modern müzecilik anlayışıyla aktaran mekanda, Selimiye'den Saray-ı Cedide-i Amire'ye, Mimar Sinan'dan Fatih'e, sultanların av sporundan Kırkpınar'a, işgalden kurtuluşa, Neolotik Dönem'den Traklar'a, ayçiçeğinden çeltiğe, Klarnetçi Deli Selim'den Kakava'ya, Kapıkule'den Meriç'e Edirne'nin dünü ve bugününe dair her bilgi, üç boyutlu silikon heykeller ve dijital ekranlarla sunulmaktadır. "),
    Place(title: "Selimiye Vakfı Müzesi", image: "images/selimiyevakıf.jpeg", category: PlaceCategory.museum, location: "  Meydan, Taş Odalar Sk. No:2, 22020 Edirne Merkez/Edirne", info: "Selimiye  Külliyesi içerisinde yer alan Dar'ül Kurra Medresesi, cami ile birlikte Osmanlı Devletinin Mimarbaşı Sinan tarafından 1569-75 yılları arasında inşa edilmiştir. Düzgün kesmetaş ve tuğla malzeme ile inşa edilen Dar'ül Kurra Medresesi'ne portal şeklinde düzenlenen bir kapı ile girilir. Ortada dikdörtgen avluyu dört yönden revak çevreler. Revağın gerisinde doğu yönde yer alan kare planlı kubbeli büyük oda dershane ve mescit; güney ve batı yöndeki odalar medrese hocaların ve öğrencilerin kaldığı odalar olarak kullanılmıştır. "),
    Place(title: "Fatih Sultan Mehmet Müzesi", image: "images/fsm.jpg", category: PlaceCategory.museum, location: " Çavuşbey Mahallesi, Hükümet Cad. 22000 Edirne Merkez/Edirne", info: "ematik olarak hazırlanan müzede, medrese hücrelerinin her bir duvarı Fatih Sultan Mehmet’in hayatından kesitlere sahne olmuştur.Saatli Medrese hücrelerinin her bir duvarı, ziyaretçisini günümüz teknolojisini kullanarak bir zaman yolculuğuna çıkarmakla birlikte, Fatih’in hayatına hasredilmiş bir kitabın sayfaları gibi tasarlanarak hareketli/hareketsiz resim ve metinlerle donatılmıştır. Yapının duvarlarına bir ara yüzey katmaksızın ilk kez bir müze yapısında wall printer uygulamasıyla resim, infografik harita ve metinler yazdırılmıştır. "),
    Place(title: "Balkan Savaşları Müzesi", image: "images/balkansavaşları.jpg", category: PlaceCategory.museum, location: "Şükrüpaşa, 22030 Edirne Merkez/Edirne ", info: " Anıt ve müze 26 Mart 1913 Balkan Savaşı ve şehitlerinin anısına yapılmış bir komplekstir. Savaş sırasında yokluk içinde Edirne’yi savunan Şükrü Paşa'nın mezarı Edirne'nin savunma yerlerinden biri olan Kıyık Tabya'ya getirilmiş ve bunun anısına bir anıt yaptırılmıştır. Anıtla birlikte burada bulunan tabyada Balkan Savaşları’nı anlatan ve Edirne halkının elinde bulunan o döneme ait eşyalardan oluşan bir müze oluşturulmuştur.")
  ];

  List<Accommodation> hotels = [
    Accommodation(title: "Marisstone Hotels", image: "images/marisstone.jpeg", info: "Edirne Keşan bölgesinde, Saros Körfezi’nin yemyeşil ormanı ile doğanın güzelliklerini gözler önüne seren butik konsept anlayışıyla hizmet vermektedir", location: "Gökçetepe Köyü, Mevkii Küme Evler No:201 Kean / Edirne, 22880", category: AccommodationCategory.hotel),
    Accommodation(title: "Hilly Otel", image: "images/hilly-hotel.jpg", info: "Edirne bölgesinde, üst kalite, spa, restoran olan otel.", location: "Şükrü Paşa Mah. Kıyık Cad. No.: 254, Edirne", category: AccommodationCategory.hotel),
    Accommodation(title: "ND Suite Otel", image: "images/ND-Suit-Hotel.jpg", info: "Edirne bölgesinde restoran olan otel", location: "Sanayi Sitesi, 29. Sokak, Edirne, Edirne, 22100", category: AccommodationCategory.hotel),
    Accommodation(title: "Fidanoğlu Suite", image: "images/fidanoglu.webp", info: "Konforlu ve huzurlu bir konaklama ile Edirne Keşan bölgesinde hizmet vermektedir .", location: "Şükrü Paşa Mah. Kıyık Cad. No.: 254, Edirne,", category: AccommodationCategory.hotel),

  ];

  List<Restaurant> restaurants = [
    Restaurant(title: "Aydın Tava Ciğer", image:"images/aydın.jpg" , info: "", location: "Sabuni, Tahmis Çarşısı Sk. No:8, 22000 Edirne Merkez/Edirne", category: RestaurantCategory.restaurant),
    Restaurant(title: "Edirneli Köfteci Osman", image: "images/osman.jpg", info: "", location: "Sarıcapaşa, Kıyık Cd. No:8, 22000 Edirne Merkez/Edirne", category: RestaurantCategory.restaurant),
    Restaurant(title: "Ciğerci Niyazi Usta", image: "images/niyazi.jpg.webp", info: "", location: "Mithat Paşa, Ortakapı Cd. No:9, 22020 Edirne Merkez/Edirne", category: RestaurantCategory.restaurant),
    Restaurant(title: "Kırkpınar Ciğercisi", image: "images/kırkpınar.jpg", info: "", location: "Sabuni, Tahmis Çarşısı Sk. No:6, 22000 Edirne Merkez/Edirne", category: RestaurantCategory.restaurant),
  ];


  List<Favorite> favorites = [
    Favorite(favoritePlace: Accommodation(title: "Marisstone Hotels", image: "images/marisstone.jpeg", info: "Edirne Keşan bölgesinde, Saros Körfezi’nin yemyeşil ormanı ile doğanın güzelliklerini gözler önüne seren butik konsept anlayışıyla hizmet vermektedir", location: "Gökçetepe Köyü, Mevkii Küme Evler No:201 Kean / Edirne, 22880", category: AccommodationCategory.hotel),category: BasePlaceCategory.accommodation),
    Favorite(favoritePlace: Accommodation(title: "ND Suite Otel", image: "images/ND-Suit-Hotel.jpg", info: "Edirne bölgesinde restoran olan otel", location: "Sanayi Sitesi, 29. Sokak, Edirne, Edirne, 22100", category: AccommodationCategory.hotel), category: BasePlaceCategory.accommodation),
    Favorite(favoritePlace: Place(title: "Balkan Savaşları Müzesi", image: "images/balkansavaşları.jpg", category: PlaceCategory.museum, location: " ", info: " "), category: BasePlaceCategory.place),
    Favorite(favoritePlace: Place(title: "Meriç Köprüsü", image: "images/meric.jpg", category: PlaceCategory.historical, location: " ", info: " "), category: BasePlaceCategory.place),

  ];

  List<ToVisit> toVisits = [
    ToVisit(toVisitPlace: Accommodation(title: "ND Suite Otel", image: "images/ND-Suit-Hotel.jpg", info: "Edirne bölgesinde restoran olan otel", location: "Sanayi Sitesi, 29. Sokak, Edirne, Edirne, 22100", category: AccommodationCategory.hotel), category: BasePlaceCategory.accommodation),
    ToVisit(toVisitPlace: Place(title: "Balkan Savaşları Müzesi", image: "images/balkansavaşları.jpg", category: PlaceCategory.museum, location: " ", info: " "), category: BasePlaceCategory.place),
    ToVisit(toVisitPlace: Place(title: "Türk ve İslam Eserleri Müzesi", image: "images/islam.jpg", category: PlaceCategory.museum, location: " Meydan, Zehrimar Cami Sok., 22020 Edirne Merkez/Edirne", info: "Edirne'de ilk müze Atatürk'ün talimatıyla 1925 yılında Selimiye Camii Dar-ül Hadis Medresesi'nde kurulmuştur. Osmanlı İmparatorluğu'nun yaklaşık 94 yıl başkentliğini yapan Edirne'de saray, halk sanatlarını etkilemiş ve etnografya açısından zenginlik kazandırmıştır. Bu yüzden ikinci bir müzeye gerek duyulmuştur.Selimiye Camii avlusu içinde bulunan Dar-üs Sıbyan Medresesi'nin, restore ettirilmesiyle Etnografya adı altında ikinci bir bölüm, Edirne'nin kurtuluşunun 13'üncü yılında (25 Kasım 1936) burada açılmıştır.İkinci Dünya Savaşından sonra Edirne Müzelerindeki eserlerin birçoğunun müzelere geri verilmesi sonucu elde kalanlar yalnızca Dar-ül Hadis Medresesi'nde sergilenmiştir.Bundan sonraki yıllarda satın alma, bağış ve kazılardan gelen eserlerle müzedeki eserlerin sayısının artması nedeniyle Edirne'de ihtiyaç duyulan yeni bir müze binası 1966 yılında programa alınmıştır. Selimiye Camii civarında müze için temin edilen arsa üzerine yapılan müze binası, 13 Haziran 1971 yılında Arkeoloji ve Etnografya Müzesi adı ile açılmış, Dar-ül Hadis Medresesindeki Müze de Türk İslam Eserleri Müzesi olarak düzenlenmiştir. "),category: BasePlaceCategory.place),
    ToVisit(toVisitPlace: Place(title: "Meriç Köprüsü", image: "images/meric.jpg", category: PlaceCategory.historical, location: " ", info: " "), category: BasePlaceCategory.place),
    ToVisit(toVisitPlace:Place(title: "Selimiye Camii", image: "images/selimiye.jpg", category: PlaceCategory.historical, location: "Meydan, Mimar Sinan Cd., 22020 Edirne Merkez/Edirne ", info: "Edirne’nin her yerinden tüm ihtişamı ile görülebilen, dört zarif minaresi, muhteşem kubbesi ile eşsiz bir yapı olan Selimiye Camii dünya tarihinin ünlü mimarlarından birisi olan Mimar Sinan’ın eseridir. Yapımına II.Selim’in emri ile 1568 yılında başlanan caminin inşası binlerce kişinin yoğun çalışması ile yedi yıl sürmüş ve 1575 yılında tamamlanmıştır. Osmanlı mimarisinin en önemli eseri olarak kabul edilen camiyi Mimar Sinan da “ustalık eserim” olarak tanımlamıştır.İlk olarak anıtsal görünümü ile dikkat çeken Selimiye Camii’nin dört köşesinde yer alan, her biri üç şerefeli minareleri ,dünyanın en görkemli örnekleri arasında gösterilmektedir. Caminin minarelerinin uzunluğu alemleri dahil 85,67 metre olarak ölçülmüştür. Minarelerin mimari açıdan dikkat çekici yönleri, mümkün olabilecek en ince şekilde tasarlanmaları ve her birinde birbiriyle çakışmadan ayrı ayrı şerefelere ulaşan üçer merdivenin bulunmasıdır.Osmanlı İmparatorluğu’nun İstanbul’dan önce başkentliğini yapmış Edirne şehrindeki Selimiye Camii ve Külliyesi, 2011 yılında UNESCO Dünya Miras Listesi’ne dahil edilmiştir."),category: BasePlaceCategory.place),
    ToVisit(toVisitPlace: Restaurant(title: "Aydın Tava Ciğer", image:"images/aydın.jpg" , info: "", location: "Sabuni, Tahmis Çarşısı Sk. No:8, 22000 Edirne Merkez/Edirne", category: RestaurantCategory.restaurant),category: BasePlaceCategory.restaurant),
    ToVisit(toVisitPlace:Restaurant(title: "Edirneli Köfteci Osman", image: "images/osman.jpg", info: "", location: "Sarıcapaşa, Kıyık Cd. No:8, 22000 Edirne Merkez/Edirne", category: RestaurantCategory.restaurant),category: BasePlaceCategory.restaurant),


  ];

}